### ISSUE TITLE
Petition for a more structured Changelogs

### ISSUE THREAD

**Issue by samcole-p1** [bseltz-cohesity/scripts#116]
Hi @bseltz-cohesity!

I've forked this repository and tested adding an automated changelog and release process to improve visibility into the changes made daily in this repo. 

The problem:

- Currently commit messages are titled after the date of their creation and do not offer insight into what was changed or why
- There is no changelog file and so users are left to using `git reflog` or the GitHub UI to see information about the commit and do their own digging
- There is no indication if a recent change has caused a previous version of a script to break or if the latest commit includes a new feature or only fixes.

The solution:

- Use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) syntax for future commits that can be used to trigger releases/changelog updates
- Add a GitHub action that handles releases and changelog updates:

[python-semantic-release](https://github.com/python-semantic-release/python-semantic-release) - my sample action (needs a GH_TOKEN secret with a PAT or fine-grained token added in for permissions)

```yaml
name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN}}
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.34.6  
        with:
          github_token: ${{ secrets.GH_TOKEN }}

```

- Add `pyproject.toml` file so python-semantic-release has metadata about the repo to work with:

```toml
[tool.repo]
name = "scripts"
version = "0.0.0"
description = "Collection of scripts for interacting with Cohesity APIs."
authors = []

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.repo.version"
]
major_on_zero = true
branch = "master"
upload_to_pypi = false
upload_to_release = false
build_command = false
```

You can view the results of the above by checking out [my fork](https://github.com/samcole-p1/scripts), but here is a sample of the resulting CHANGELOG file, all without having to create or manage it yourself:

```md
# Changelog

<!--next-version-placeholder-->

## v0.1.0 (2023-07-25)

### Feature

* Add release workflow ([`008157c`](https://github.com/samcole-p1/scripts/commit/008157cd5b76a48d8217c2dd3dd1bbbb14c5408c))

### Fix

* Updated release workflow ([`8dbca77`](https://github.com/samcole-p1/scripts/commit/8dbca778d84ee08ff247a50f3467f7167260f47b))

```

This is available to be merged upstream, just let me know.
