### ISSUE TITLE
globalWhiteList.py has no support for -pwd switch

### ISSUE THREAD

**Issue by amlucent** [bseltz-cohesity/scripts#92]
I am utilizing your excellent python scripts to manage a fleet of cohesity arrays mostly for smartfiles.  I am actually using them through ansible as my preferred method, because tbh the canned cohesity ansible modules are (greatly) lacking.  In general I prefer to use ansible vault for secrets and I just pass them along as a variable shown below.  I appreciate that the -pwd switch is not a recommended solution but I am confident in vaults ability to protect my credentials, integrate seemlessly with ansible, and even scale to support a whole fleet of clusters with rotating service accounts/passwords as is best practice.  

The following execution of the globalWhiteList.py yields an error as it has no support for -pwd switch.
```yaml
task:
  name: Setup Global Whitelist on Target Cluster
  delegate_to: localhost
  ansible.builtin.shell: /usr/bin/python3 /local/path/to/cohesity-scripts/python/golbalWhiteList/globalWhiteList.py -v {{ inventory_hostname }} -u {{ cohesity_user }} -pwd {{ cohesity_passwd }} -d local -a -c {{ allowed_cidr }}
```

Thank you again for creating these scripts, I am getting a lot of milage out of them!
